# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Note that the environment variables used for the ast-scan job are defined in CircleCI, not in GitHub.
jobs:
  ast-scan:
    docker:
      - image: checkmarx/ast-cli:latest
    steps:
      - checkout
      - run:
          name: AST Scan
          command: |
            /app/bin/cx --debug \
                        --client-id "${AST_CLIENT_ID}" \
                        --client-secret "${AST_CLIENT_SECRET}" \
                        --base-uri "${AST_BASE_URI}" \
                        --tenant "${AST_TENANT}" scan create \
                        -s . \
                        --project-name "${CIRCLE_PROJECT_REPONAME}" \
                        --branch "${CIRCLE_BRANCH}" \
                        --scan-types sast

workflows:
  ast-scan:
    jobs:
      - ast-scan
